---
title: "Explorative stats for Clinical Chemistry parameters"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float:
      toc_collapsed: true
---

## Setup

```{r}
# Source utility functions
source("/home/rstudio/repo_files/scripts/util_dataset.R ")
source("/home/rstudiorepo_files/scripts/util_display.R")
source("/home/rstudio/repo_files/scripts/util_calculations.R")
```

```{r}
# Define parameters of interest
PARAM_CODE <- c("D3")
```

```{r}
# Import packages
library(tidyr)
library(dplyr)
library(purrr)
library(stringr)
library(readxl)
library(googledrive)
library(ggplot2)
library(ggsci)
library(ggpubr)
library(plotly)
library(DT)
```

```{r}
# Set how Google Drive authentication should be done
drive_auth(cache = "/home/rstudio/local_files/.secrets", use_oob = TRUE)
```

```{r}
# Download from drive
main_table <- PARAM_CODE %>%
  paste(LAB_DB_LOCATION, ., ".txt.gz", sep="") %>%
  map(read_from_drive) %>%
  bind_rows()
```

```{r warning=FALSE}
# Add gender information to main table and format values to numeric
main_table <- main_table %>%
  mutate(
    serum_level = as.numeric(value_n),
    DATE = as.Date(date, format = "%Y.%m.%d"),
    gender = case_when(
      gender == "m" ~ "Male",
      gender == "f" ~ "Female",
      TRUE ~ "Unknown"
    )
  ) %>%
  add_count(gender) %>%
  mutate(
    gender = paste(gender, " (", n, ")", sep="")
  ) %>%
  select(-n)

female_label <- main_table %>%
  filter(grepl("Female", gender)) %>%
  .$gender %>%
  unique()

male_label <- main_table %>%
  filter(grepl("Male", gender)) %>%
  .$gender %>%
  unique()

other_label <- main_table %>%
  filter(grepl("Unknown", gender)) %>%
  .$gender %>%
  unique()

main_table <- main_table %>%
  mutate(
    gender = factor(gender, levels=c(female_label, male_label, other_label))
  )
```

## Basic descriptive statistics

### DB health check

```{r warning=FALSE}
tmp_table <- main_table %>%
  add_count(is_numeric) %>%
  mutate(
    is_numeric = ifelse(is_numeric == "N", "Numerical result", "Parametric or comented"),
    is_numeric = paste(is_numeric, " (", n, ")", sep="")
  )

numres_label <- tmp_table %>%
  filter(grepl("Numerical result", is_numeric)) %>%
  .$is_numeric %>%
  unique()

parres_label <- tmp_table %>%
  filter(grepl("Parametric or comented", is_numeric)) %>%
  .$is_numeric %>%
  unique()

p <- tmp_table %>%
  mutate(
    is_numeric = factor(is_numeric, levels=c(parres_label, numres_label))
  ) %>%
  ggplot(aes(x=param, fill=is_numeric)) + 
  geom_histogram(position="stack", stat="count") +
  scale_fill_npg() +
  theme_bw() +
  theme(
    axis.text.x = element_text(angle=30, vjust=0.5, hjust=1)
  ) +
  labs(title="Number of measurements per parameter code", x="", y="")

ggplotly(p)
```

### Distribution of measurements by gender

```{r warning=FALSE}
p <- main_table %>%
  ggplot(aes(x=serum_level, fill=gender)) + 
  geom_density(alpha=0.6) +
  scale_fill_npg() +
  theme_bw() +
  theme(
    axis.text.x = element_text(angle=30, vjust=0.5, hjust=1)
  ) +
  labs(title="Distribution of measurements by gender", x="", y="")

ggplotly(p)
```

### Normal range and outliers

### Outliers based on quantiles

```{r}
median_iqr_table <- main_table %>%
  filter(is_numeric == "N") %>%
  group_by(gender) %>%
  summarize(calc_quantile_boundaries(serum_level))
         
show_tab(median_iqr_table)
```

```{r warning=FALSE}
main_table %>%
  filter(is_numeric == "N") %>%
  plot_ly(
    x = ~gender, y = ~serum_level, type = "box", color=color_names[1],
    boxpoints = FALSE, width=800, height=600
  ) %>%
  layout(
    xaxis = list(title="", tickangle = 30, tickfont=list(size=12)),
    legend = list(orientation="h", xanchor="center", x=0.5)
  )
```

```{r warning=FALSE}
main_table %>%
  filter(is_numeric == "N") %>%
  plot_ly(
    x = ~gender, y = ~serum_level, type = "violin", color=color_names[1],
    boxpoints = FALSE, width=800, height=600
  ) %>%
  layout(
    xaxis = list(title="", tickangle = 30, tickfont=list(size=12)),
    legend = list(orientation="h", xanchor="center", x=0.5)
  )
```

## Change in characteristics by time

### Stability of measurement medians

```{r warning=FALSE}
median_iqr_by_date <- main_table %>%
  filter(is_numeric == "N") %>%
  mutate(
    month = format(DATE, "%m"),
    year = format(DATE, "%Y"),
    year_month = paste(year, month)
  ) %>%
  group_by(year_month) %>%
  summarize(calc_quantile_boundaries(serum_level))
    
show_tab(median_iqr_by_date)
```

```{r}
p <- median_iqr_by_date %>%
  arrange(year_month) %>%
  mutate(
    group = "",
    year_month = paste(year_month, "01"),
    year_month = as.Date(year_month, format="%Y %m %d")
  ) %>%
  ggplot() +
  geom_line(aes(y=MEDIAN, x=year_month, group=group), color=color_names[1]) +
  geom_ribbon(aes(ymin=LB, ymax=UB, x=year_month), fill=color_names[2], alpha=0.3) +
  scale_x_date(date_labels = "%m-%Y") +
  labs(
    title = "Median +/- 1.5 IQR by month", x = "Date", y = paste(PARAM_CODE, "serum level")
  )
ggplotly(p)
```

