---
title: "Quality Control comparing precision across sites"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float:
      toc_collapsed: true
---

## Setup

```{r}
# Import tools to be used

library(tidyr)
library(dplyr)
library(purrr)
library(stringr)
library(readxl)
library(googledrive)
library(ggplot2)
library(ggsci)
library(plotly)
library(DT)
library(knitr)

control_sheet_location <- '~/Internal controls'
query_string <- '9\\.\\s*hét'
```

```{r}
# Set how Google Drive authentication should be done

drive_auth(cache = "/home/rstudio/local_files/.secrets", use_oob = TRUE)
```

## Parse raw files

```{r message = FALSE, warning = FALSE}
# Define function that opens table from drive

read_controlfile_from_drive <- function(drive_id) {
  path <- drive_get(id = drive_id)
  drive_download(path, overwrite = TRUE)
  data_file <- path$name
  data_table <- read_excel(data_file)
  data_table$file_name <- data_file
  unlink(data_file)
  return(data_table)
}

t1 <- read_controlfile_from_drive('1J4-FYXHh0wS69evdVRwIU9WIZE3PknH7')
datatable(t1)
```

```{r}
# Define a function to tidy up by renaming columns first

tidyup_raw_colnames <- function(in_df) {
  
  sample_tags <- unlist(in_df[1,])
  
  mach_names <- in_df %>%
    colnames() %>%
    {!grepl('^\\.\\.', .)} %>%
    which() %>%
    setNames(colnames(in_df)[.], .)
  
  coltags <- mach_names %>%
    names() %>%
    head(1) %>%
    as.numeric() %>%
    {rep("X", .-1)}
    
  for (i in seq(1, length(mach_names) - 1)){
    pp <- as.numeric(names(mach_names))
    mach <- mach_names[[i]]
    coltags <- c(coltags, rep(mach, pp[[i+1]] - pp[[i]]))
  }
  coltags <- c(coltags, tail(mach_names, 1))
  
  column_meta <- data.frame(
    mach_tag = coltags, sample_tag = sample_tags, stringsAsFactors = FALSE
  )
  column_meta$colunique <- ifelse(
    column_meta$mach_tag %in% c("X", "file_name"), colnames(in_df),
    paste("M_", column_meta$sample_tag, column_meta$mach_tag, sep = "")
  )
  
  colnames(in_df) <- c("Param", "Unit", column_meta$colunique[c(-1, -2)])
  
  in_df <- in_df %>%
    .[c(-1, -2),] %>%
    pivot_longer(-one_of("Param", "Unit", "file_name")) %>%
    left_join(column_meta, by = c(name = "colunique"))
  
  return(in_df)
  
}

t2 <- tidyup_raw_colnames(t1)
datatable(t2)
```

```{r}
# Finally, wrap it all up into a single function

tidyup_raw_file <- function(in_df){
  in_df %>%
    tidyup_raw_colnames() %>%
    mutate(
      Site = file_name %>%
        str_extract("\\s+[A-ZÓ]*\\s+\\d+\\.\\s*hét") %>%
        str_replace("\\d+\\.\\s*hét", "") %>%
        trimws(),
      Mach = mach_tag,
      Sample = paste("M", sample_tag, sep = "_"),
      Value = value
    ) %>%
    select(Site, Mach, Sample, Param, Unit, Value)
}

t1 %>%
  tidyup_raw_file() %>%
  datatable()
```

```{r message = FALSE, warning = FALSE}
# Download all results matching the query pattern

main_data <- control_sheet_location %>%
  drive_ls() %>%
  filter(grepl(query_string, name)) %>%
  .$id %>%
  map(read_controlfile_from_drive) %>%
  map(tidyup_raw_file) %>%
  bind_rows() %>%
  filter(!(Param %in% c(NA, "44258")))

datatable(main_data)
```

## Show comparison for each Param

```{r message = FALSE, warning = FALSE}
# Interactively explore correlations between measurements

color_names <- main_data %>%
  .$Sample %>%
  unique() %>%
  setNames(pal_npg()(length(.)), .)

plotly_dt <- main_data  %>%
  group_by(Param) %>%
  group_split() %>%
  setNames(unique(main_data$Param)) %>%
  imap(function(dt, nm) {
    list(data = dt, visible = FALSE)
  }
  )

plotly_dt[1][[1]]$visible = TRUE
steps <- list()
ply <- plot_ly(height = 600, width = 800)

for (i in seq_along(plotly_dt)) {
    segment_dt <- plotly_dt[[i]]
    SDT <- segment_dt$data
    UNIT <- paste(unique(SDT$Unit), collapse=";")
    N <- length(unique(SDT$Sample))
    
    for (SMPL in unique(SDT$Sample)) {
      FDT <- SDT %>%
        filter(Sample == SMPL) %>%
        arrange(Mach)
      color <- color_names[SMPL]
      
      ply <- add_trace(
        ply, x = FDT$Mach, y = FDT$Value, name = SMPL, type = "scatter",
        mode = 'lines+markers', visible = segment_dt$visible, hoverinfo = "text",
        text = paste("<b>Value</b>:", FDT$Value, "<br><b>Machine</b>:", FDT$Mach),
        marker = list(color = color), line = list(color = color)
      )
    }
    
    step <- list(
      args = list('visible', rep(FALSE, N*length(plotly_dt))),
      method = 'restyle',
      label = paste(names(plotly_dt)[[i]], "[", UNIT, "]")
    )
    
    step$args[[2]][seq(1+N*(i-1), N+N*(i-1))] = TRUE  
    steps[[i]] = step
  }

slider_settings <- list(
  list(
    active = 0, currentvalue = list(prefix = "Param: "),
    steps = steps, pad = list(t = 90)
  )
)

layout(
  ply, plot_bgcolor  = 'rgba(0, 0, 0, 0)', paper_bgcolor = 'rgba(0, 0, 0, 0)',
  autosize = FALSE, sliders = slider_settings, shapes = lines,
  xaxis = list(
    tickangle = 30, title = list(text = ""), showgrid = FALSE
  ),
  yaxis = list(title = list(text = "Serum level"), showgrid = FALSE)
)
```

## Percent difference from mean
### Calculation tables

```{r message = FALSE, warning = FALSE}
# Calculate percent difference from mean

mean_measured_values <- main_data %>%
  group_by(Param, Sample) %>%
  mutate(
    Base_mean = round(mean(Value, na.rm = TRUE), 3)
  ) %>%
  ungroup() %>%
  distinct(Param, Sample, Base_mean)

datatable(mean_measured_values)
```

```{r message = FALSE, warning = FALSE}
# Calculate percent difference from mean

pct_diff_values <- main_data %>%
  left_join(mean_measured_values, by = c("Param", "Sample")) %>%
  mutate(
    pct_diff = 100* (Value - Base_mean) / Base_mean
  )

datatable(pct_diff_values)
```

### Difference by Machine

```{r message = FALSE, warning = FALSE}
# Interactively show pct_differences by site / machine

for (MCH in unique(pct_diff_values$Mach)) {
  gg <- pct_diff_values %>%
    filter(Mach == MCH) %>%
    mutate(
      Param = paste(Param, "[", Unit, "]"),
      PCT = paste(round(pct_diff, 2), "%", sep = ""),
      pct_diff = pct_diff / 100
    ) %>%
    ggplot(aes(
      x = Param, y = pct_diff, color = Sample, label1 = PCT,
      label2 = Value, label3 = Base_mean, label4 = Unit
    )) +
    geom_jitter(position=position_jitter(0.2), cex=0.5) +
    geom_hline(
      yintercept = c(-0.05, 0.05), linetype = "dashed", color = "red", size = 0.1
    ) +
    #facet_grid("Mach") +
    scale_y_continuous(labels = scales::percent_format(), limits = c(-0.15, 0.15)) +
    scale_color_npg() +
    theme_bw() +
    theme(
        panel.grid.major = element_blank(),
        axis.text.x = element_text(angle = 30, hjust = 1), 
    ) +
    labs(x = "", y = "Percent difference from mean", title = MCH)
  
  p <- gg %>%
    ggplotly(
      tooltip = c("x", "label1", "label2", "label3", "label4"),
      height = 300, width = 800
    ) %>%
    layout(
      plot_bgcolor  = 'rgba(0, 0, 0, 0)', paper_bgcolor = 'rgba(0, 0, 0, 0)'
    )
  print(p)
}
```

### Difference by Sample

```{r message = FALSE, warning = FALSE}
# Interactively show pct_differences by sample

for (SMPL in unique(pct_diff_values$Sample)) {
  gg <- pct_diff_values %>%
    filter(Sample == SMPL) %>%
    mutate(
      Param = paste(Param, "[", Unit, "]"),
      PCT = paste(round(pct_diff, 2), "%", sep = ""),
      pct_diff = pct_diff / 100
    ) %>%
    ggplot(aes(
      x = Param, y = pct_diff, color = Mach, label1 = PCT,
      label2 = Value, label3 = Base_mean, label4 = Unit
    )) +
    geom_jitter(position=position_jitter(0.2), cex=0.5) +
    geom_hline(
      yintercept = c(-0.05, 0.05), linetype = "dashed", color = "red", size = 0.1
    ) +
    #facet_grid("Mach") +
    scale_color_npg() +
    scale_y_continuous(labels = scales::percent_format(), limits = c(-0.15, 0.15)) +
    theme_bw() +
    theme(
        panel.grid.major = element_blank(),
        axis.text.x = element_text(angle = 30, hjust = 1), 
    ) +
    labs(x = "", y = "Percent difference from mean", title = paste("Sample tested:", SMPL))
  
  p <- gg %>%
    ggplotly(
      tooltip = c("x", "label1", "label2", "label3", "label4"),
      height = 300, width = 800
    ) %>%
    layout(
      plot_bgcolor  = 'rgba(0, 0, 0, 0)', paper_bgcolor = 'rgba(0, 0, 0, 0)'
    )
  print(p)
}
```





